apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: "elasticsearch"
    port: 9200
    targetPort: 9200
  - name: "elasticsearch-api"
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
  type: ClusterIP
