apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
        - name: elk
          image: sebp/elk:E1L1K4
          ports:
            - containerPort: 9200
            - containerPort: 5044
            - containerPort: 5601
          volumeMounts:
            - name: logstash-data
              mountPath: /var/log/logstash
            - name: kibana-data
              mountPath: /var/log/kibana   
            - name: elasticseach-data
              mountPath: /var/lib/elasticsearch     
            - name: elasticseach-data1
              mountPath: /var/log/elasticsearch                
      volumes:
      - name: logstash-data
        emptyDir: {}
      - name: kibana-data
        emptyDir: {}
      - name: elasticseach-data
        emptyDir: {}
      - name: elasticseach-data1
        emptyDir: {}
