apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
  - name: "logstash"
    port: 5044
    targetPort: 5044
  - name: "logstash-api"
    port: 9600
    targetPort: 9600
  selector:
    app: logstash
  type: ClusterIP
