apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
