apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:6.1.1
          ports:
            - containerPort: 5601
