apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash.conf
data:
  logstash.conf: |
    input {
      stdin { }
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch { hosts => ["elasticsearch:9200"] }
      stdout { codec => rubydebug }
   }
